import re
from io import BytesIO
from typing import Any

from fpdf import FPDF


def _clean_text(text: str) -> str:
    """Normalize text for PDF output."""
    text = text or ""
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    text = re.sub(r"#{1,6}\s*", "", text)
    text = text.replace("\r\n", "\n")
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _safe_filename(topic: str) -> str:
    slug = re.sub(r"[^\w\s-]", "", topic or "research").strip().lower()
    slug = re.sub(r"[\s_-]+", "_", slug)
    return (slug[:60] or "research_report") + ".pdf"


class ResearchPDF(FPDF):
    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, "Generated by ResearchMind", align="C")


def generate_research_pdf(research: dict[str, Any]) -> tuple[bytes, str]:
    """Build a PDF bytes payload and suggested filename from research data."""
    pdf = ResearchPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    line_width = pdf.w - pdf.l_margin - pdf.r_margin

    topic = _clean_text(research.get("topic", "Research Report"))
    pdf.set_font("Helvetica", "B", 16)
    pdf.multi_cell(line_width, 10, topic)
    pdf.ln(4)

    overview = _clean_text(research.get("overview", ""))
    if overview:
        pdf.set_font("Helvetica", "I", 11)
        pdf.multi_cell(line_width, 6, overview)
        pdf.ln(4)

    report = _clean_text(research.get("report", ""))
    if report:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Research Report", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(line_width, 6, report)
        pdf.ln(4)

    findings = research.get("key_findings") or []
    if findings:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Key Findings", ln=True)
        pdf.set_font("Helvetica", "", 11)
        for index, finding in enumerate(findings, start=1):
            text = _clean_text(finding.get("finding", ""))
            pdf.multi_cell(line_width, 6, f"{index}. {text}")
            pdf.ln(2)

    conclusion = _clean_text(research.get("conclusion", ""))
    if conclusion:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Conclusion", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.multi_cell(line_width, 6, conclusion)
        pdf.ln(4)

    sources = research.get("sources") or []
    if sources:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Sources & References", ln=True)
        pdf.set_font("Helvetica", "", 10)
        for index, source in enumerate(sources, start=1):
            title = _clean_text(source.get("title", "Untitled"))
            url = _clean_text(source.get("url", ""))
            date = _clean_text(source.get("date", "Unknown date"))
            pdf.multi_cell(line_width, 5, f"{index}. {title} ({date})")
            if url:
                pdf.set_text_color(0, 0, 180)
                pdf.multi_cell(line_width, 5, url)
                pdf.set_text_color(0, 0, 0)
            pdf.ln(2)

    generated_at = _clean_text(str(research.get("generated_at", "")))
    if generated_at:
        pdf.ln(4)
        pdf.set_font("Helvetica", "I", 9)
        pdf.cell(0, 6, f"Generated at: {generated_at}", ln=True)

    buffer = BytesIO()
    pdf.output(buffer)
    return buffer.getvalue(), _safe_filename(topic)
